### ISSUE TITLE
Take a look at `.editorconfig`

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sommerfeld-io/template-repository#19]
### See
https://github.com/sebastian-sommerfeld-io/poc-gatling

- devcontainer.json (plugin)
- .editorconfig
- cleanup .vscode/settings.json

### Todo

- [x] Adopt config
- [x] Move Dev Container into a dedicated docker image "dev-container"
- [x] Keep Dockerfile in repos, but extend image "dev-container" ... this way dependabot tracks updates and individual tools can still be installed

### Roll out to all repositories

- [x] https://github.com/sommerfeld-io/.github
- [x] https://github.com/sommerfeld-io/template-repository
- [x] https://github.com/sommerfeld-io/configs-homelab
- [x] https://github.com/sommerfeld-io/container-images
